### ISSUE TITLE
Can't run individual tests 

### ISSUE THREAD

**Issue by MariaAga** [theforeman/foreman-js#115]
## I'm submitting a…
* [ ] Regression (a behavior that used to work and stopped working in a new release)
* [x] Bug report 
* [ ] Feature request
* [ ] Documentation issue or request
* [ ] Support request

## Expected Behavior
Before using foreman/tests you could run individual test using `npm test -- TestName`

## Current Behavior
 now this command  (`-- TestName`)  runs all tests.
the `-- -u` flag is working as expected.

@amirfefer

**Comment by amirfefer** [comment]
Try `npm test -- -- <FILE>`
I'll add it to the docs

**Comment by sharvit** [comment]
Thanks @amirfefer, anything we can change to avoid using `-- --`?
Maybe the `commander` be used for that?
