### ISSUE TITLE
Snapshots are failing

### ISSUE THREAD

**Issue by laviro** [theforeman/foreman-js#130]
## I'm submitting a…

* [ ] Regression (a behavior that used to work and stopped working in a new release)
* [X] Bug report 
* [ ] Feature request
* [ ] Documentation issue or request
* [ ] Support request

## Expected Behavior
Snapshots should pass

## Current Behavior
Snapshots are failing after one of the latest libraries upgrade

## Possible Solution
find the library that caused it and pin to the last version

## Steps to Reproduce (for bugs)
run tests, or see latest travis runs, e.g: https://travis-ci.org/github/theforeman/foreman/jobs/665423667

## Environment

* @theforeman/test@4.2.1
* foreman-js version: 4.2.1
* Node version: v12.14.1
* NPM version: 6.13.4 
* Operating system: Linux

**Comment by sharvit** [comment]
Thanks for reporting @laviro :+1: 

I don't see any snapshot failures in your Travis job but I do see it failed about publishing coverage.

**Comment by laviro** [comment]
Seems like a caching issue.. solved on yesterday evening by itself, closing this issue
