### ISSUE TITLE
Include @patternfly/react-charts in foreman-js

### ISSUE THREAD

**Issue by sjha4** [theforeman/foreman-js#297]
Opening this to discuss if other plugins are using this? 
I specifically need the DonutChart to present task progress so open to other suggestions based on implementation in other projects.
This works for me right now by adding @patternfly/react-charts to katello package.json dependency:

```
<ChartDonut
   ariaDesc="Publishing Content View"
   ariaTitle="Publishing Content View"
   data={[{ x: 'Completed', y: progress}, { x: 'Pending', y: 100 - progress}]}
   labels={({ datum }) => `${datum.x}: ${datum.y}%`}
   title="Publishing"
   colorScale={taskErrored? ['#FF0000', '#F08080'] : ['#008000', '#8FBC8F']}
 />
```

**Comment by ezr-ondrej** [comment]
I believe the `@patternfly/react-charts` are PF4 charts, right?
I think those are not used anywhere in Foreman, but we would definitelly love to add them (migrate to PF4 charts).
If you'd be able to open a PR to foreman that would migrate one type of charts

**Comment by ezr-ondrej** [comment]
Is this done as of https://github.com/theforeman/foreman-js/pull/298 got merged?

**Comment by ezr-ondrej** [comment]
Closing here as this is not the best thread to go deeper on the topic, but thanks for opening and adding the library! :+1:
