### ISSUE TITLE
The dist file contains only the production version of react

### ISSUE THREAD

**Issue by sharvit** [theforeman/foreman-js#4]
The dist file contains only the production version of React.

## I'm submitting a…

* [ ] Regression (a behavior that used to work and stopped working in a new release)
* [x] Bug report 
* [x] Feature request
* [ ] Documentation issue or request
* [ ] Support request

## Expected Behavior

When running webpack dev server, it should use the development version of `react`.

## Current Behavior

When running webpack dev server, it uses the production version of `react`.

See how react manipulate the building results:
https://github.com/facebook/react/blob/master/packages/react/npm/index.js

Other libraries might do so as well.

## Possible Solution

`@theforeman/vendor` can produce two different builds (production, development) by using different `NODE_ENV` value.

**Comment by tbrisker** [comment]
I'm a bit hesitant to create different build for prod and dev since part of the incentive for the vendor package is to use the same artifact for both, but perhaps there's no good solution here.

**Comment by sharvit** [comment]
> I'm a bit hesitant to create different build for prod and dev since part of the incentive for the vendor package is to use the same artifact for both, but perhaps there's no good solution here.

Agree but I can't think about a better solution as well.

IMO we should support consumers in a transparent way:
```bash
rake webpack:compile # should use the `production` version
foreman start # should use the `development` version with `webpack-dev-server`
RAILS_ENV|NODE_ENV=production foreman start # should use the `production` version with `webpack-dev-server`
```

We can update the [webpack.plugin.js](https://github.com/theforeman/foreman-js/blob/master/packages/vendor/webpack.plugin.js) so it will be transparent for consumers.

**Comment by tbrisker** [comment]
Ok, i guess that makes sense, as long as we can still run the production version in development if needed that's already better than what we have now (that node-production build differs from the release build)

**Comment by waldenraines** [comment]
This makes sense to me as well, we should also update any relevant documentation so people are aware of this.
